/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package task_6

import java.io.File
import java.util.*
import kotlin.collections.ArrayList
import kotlin.collections.HashMap

class App {
    //308143 is not right
    fun solveFirst(input: List<String>): Int {
        val objects = HashMap<String, Node>()

        for (line in input) {
            val parts = line.split(")")

            val parentName = parts[0]
            val parent = objects.getNode(parentName)

            val childName = parts[1]
            val child = objects.getNode(childName)

            append(parent, child)
        }

        val com = objects.getValue("COM")
        return getTotalOrbits(com)
    }

    private fun getTotalOrbits(root: Node): Int {
        var result = 0

        val nodesToVisit = Stack<Pair<Node, Int>>()
        nodesToVisit.push(Pair(root, 0))

        while (nodesToVisit.isNotEmpty()) {
            val (node, level) = nodesToVisit.pop()
            result += level

            nodesToVisit.addAll(node.children.map { Pair(it, level + 1) })
        }

        return result
    }

    fun solveSecond(input: List<String>): Int {
        return -1
    }

    private fun append(parent: Node, child: Node) {
        child.parent = parent
        parent.children.add(child)
    }

    fun MutableMap<String, Node>.getNode(name: String): Node {
        if (this.containsKey(name)) {
            return this.getValue(name)
        }

        val newNode = Node(name, null, ArrayList())
        this[name] = newNode

        return newNode
    }
}

data class Node(val name: String, var parent: Node?, val children: MutableList<Node>)

fun main() {
    val app = App()
    val input = File("input.txt").readLines()

    println(app.solveFirst(input))
    println(app.solveSecond(input))
}
