/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package task_6

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val app = App()
        assertEquals(42, app.solveFirst(listOf(
                "COM)B",
                "B)C",
                "C)D",
                "D)E",
                "E)F",
                "B)G",
                "G)H",
                "D)I",
                "E)J",
                "J)K",
                "K)L"
        )))
    }
}
