/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package task_5

import kotlin.test.Test

class Task5Test {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = Task5()
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
