/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package task_5

import java.io.File
import java.lang.RuntimeException

class Task5 {
    fun solveFirst(input: String): Int {
        val state = getStateByInput(input)

        val inputValue = 1
        var outputValue = 0

        var ptr = 0
        var ptrInc = 0

        while (true) {
            var finished = false
            val num = state[ptr]

            var opcode = num
            var firstOperandMode = Mode.POSITION
            var secondOperandMode = Mode.POSITION

            if (num.specifiesParamMode()) {
                val parameterModes = num.toString()
                opcode = parameterModes[3].toString().toInt()
                firstOperandMode = Mode.of(parameterModes[1])
                secondOperandMode = Mode.of(parameterModes[0])
            }

            when (opcode) {
                1 -> {
                    ptrInc = state.opcodeAdd(ptr, firstOperandMode, secondOperandMode)
                }
                2 -> {
                    ptrInc = state.opcodeMult(ptr, firstOperandMode, secondOperandMode)
                }
                3 -> {
                    ptrInc = state.opcodeSaveTo(ptr, inputValue)
                }
                4 -> {
                    val result = state.opcodeGetFrom(ptr)
                    outputValue = result.first
                    ptrInc = result.second
                }
                99 -> {
                    println("Finished")
                    finished = true
                }
                else -> {
                    println("unknown value of $num")
                }
            }

            if (finished) break
            ptr += ptrInc
        }

        return outputValue
    }

    fun solveSecond(input: String): Int {
        return -1
    }

    fun Int.specifiesParamMode(): Boolean {
        return this > 1000
    }

    fun MutableList<Int>.opcodeAdd(ptr: Int, firstOperand: Mode, secondOperand: Mode): Int {
        val first = firstOperand.get(this, ptr + 1)
        val second = secondOperand.get(this, ptr + 2)
        val resultPtr = Mode.IMMEDIATE.get(this, ptr + 3)

        this[resultPtr] = first + second

        return 4
    }

    fun MutableList<Int>.opcodeMult(ptr: Int, firstOperand: Mode, secondOperand: Mode): Int {
        val first = firstOperand.get(this, ptr + 1)
        val second = secondOperand.get(this, ptr + 2)
        val resultPtr = Mode.IMMEDIATE.get(this, ptr + 3)

        this[resultPtr] = first * second

        return 4
    }

    fun MutableList<Int>.opcodeSaveTo(ptr: Int, input: Int): Int {
        val resultPtr = Mode.IMMEDIATE.get(this, ptr + 1)

        this[resultPtr] = input

        return 2
    }

    fun MutableList<Int>.opcodeGetFrom(ptr: Int): Pair<Int, Int> {
        val resultPtr = Mode.IMMEDIATE.get(this, ptr + 1)

        return Pair(this[resultPtr], 2)
    }

    private fun getStateByInput(input: String) = input.split(',').map { it.toInt() }.toMutableList()
}

enum class Mode {
    POSITION {
        override fun get(state: List<Int>, ptr: Int): Int = state.getPositionMode(ptr)
    },
    IMMEDIATE {
        override fun get(state: List<Int>, ptr: Int): Int = state.getImmediateMode(ptr)
    };

    abstract fun get(state: List<Int>, ptr: Int): Int

    companion object {
        fun of(value: Char): Mode {
            return when (value) {
                '0' -> POSITION
                '1' -> IMMEDIATE
                else -> throw RuntimeException("Unknown mode value of $value")
            }
        }
    }
}

fun List<Int>.getPositionMode(index: Int): Int = this[this[index]]
fun List<Int>.getImmediateMode(index: Int): Int = this[index]


fun main() {
    val task5 = Task5()
    val input = File("input.txt").readLines()[0]

//    print(task5.solveFirst("1002,4,3,4,33,99"))
    print(task5.solveFirst(input))
    print(task5.solveSecond(input))
}
