/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package task_8

import java.io.File

class App(private val width: Int, private val height: Int) {
    fun solveFirst(input: List<Int>): Int {
        val image = getImage(input)

        var minZerosCount = width * height + 1
        var minZerosLayer: List<Int> = image.layers[0]
        for (layer in image.layers) {
            val zerosCount = digitCount(layer, 0)
            if (zerosCount < minZerosCount) {
                minZerosCount = zerosCount
                minZerosLayer = layer
            }
        }

        return digitCount(minZerosLayer, 1) * digitCount(minZerosLayer, 2)
    }

    private fun digitCount(layer: List<Int>, digit: Int) = layer.filter { it == digit }.count()

    private fun getImage(input: List<Int>): Image {
        val image = Image()

        var layer = image.newLayer()

        var pixelNum = 0
        for (pixel in input) {
            if (pixelNum == width * height) {
                layer = image.newLayer()
                pixelNum = 0
            }

            pixelNum++
            layer.add(pixel)
        }

        return image
    }

    fun solveSecond(input: List<Int>): Int {
        return -1
    }

}

class Image {
    val layers = mutableListOf<MutableList<Int>>()

    fun newLayer(): MutableList<Int> {
        val newLayer = mutableListOf<Int>()

        layers.add(newLayer)

        return newLayer
    }
}

fun main() {
    val app = App(25, 6)
    val input = File("input.txt").readLines()[0].map { it.toString().toInt() }

    println(app.solveFirst(input))
    println(app.solveSecond(input))
}